var subject = require('./subject.js')
var mock = require('mock-fs');
var faker = require('faker');
subject.inc('',undefined);
subject.inc('',"somestring");
subject.inc(1,"somestring");
subject.inc(-1,"somestring");
subject.inc(-1,"somestring");
subject.fileTest('path/fileExists','');
subject.fileTest('path/fileExists','path/fileExists');
subject.fileTest('path/fileExists','pathContent/file1');
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize(faker.phone.phoneNumberFormat());
subject.format(faker.phone.phoneNumberFormat(),'',{"normalize":true});
subject.blackListNumber("212-313-5151");
subject.blackListNumber('othernumber');
subject.blackListNumber(faker.phone.phoneNumberFormat());
